services:
  db:
    image: postgres:17.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: nextone4/nextone-back-staging:latest
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NEXTONE_COMPANY_ID=${NEXTONE_COMPANY_ID}
    healthcheck:
      test:
        - CMD-SHELL
        - 'curl -f http://localhost:4005/graphql?query=%7B__typename%7D -H "Apollo-Require-Preflight: true" || exit 1'
      interval: 10s
      timeout: 30s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: nextone4/nextone-front-staging:latest
    environment:
      - VITE_API_URL=http://api_gateway/api
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --request GET --url 'http://localhost:5173' || exit 1"
      interval: 5s
      timeout: 5s
      retries: 20

  api_gateway:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    ports:
      - 3030:80

  e2e:
    build: ./e2e
    volumes:
      - ./playwright-report:/app/playwright-report
    depends_on:
      api_gateway:
        condition: service_started
    environment:
      - NODE_ENV=development
      - PLAYWRIGHT_BASE_URL=http://api_gateway
      - BACKEND_URL=http://api_gateway/api

volumes:
  postgres_data:
